const imagesPaths = {
    freezing_rain_heavy: './img/freezing_rain.svg',
    freezing_rain: './img/freezing_rain.svg',
    freezing_rain_light: './img/freezing_rain.svg',
    freezing_drizzle: './img/freezing_rain.svg',
    ice_pellets_heavy: './img/ice_pellets.svg',
    ice_pellets: './img/ice_pellets.svg',
    ice_pellets_light: './img/ice_pellets.svg',
    snow_heavy: './img/snow.svg',
    snow: './img/snow.svg',
    snow_light: './img/snow.svg',
    flurries: './img/flurries.svg',
    tstorm: './img/tstorm.svg',
    rain_heavy: './img/rain.svg',
    rain: './img/rain.svg',
    rain_light: './img/light_rain.svg',
    drizzle: './img/drizzle.svg',
    fog_light: './img/fog.svg',
    fog: './img/fog.svg',
    cloudy: './img/cloudy.svg',
    mostly_cloudy: './img/mostly_cloudy.svg',
    partly_cloudy: './img/partly_cloudy.svg',
    mostly_clear: './img/partly_cloudy.svg',
    clear: './img/clear.svg',
};

export default imagesPaths;
