const localization = {
    en: {
        feels: 'FEELS LIKE:',
        wind: 'WIND:',
        wind_unit: 'M/S',
        humidity: 'HUMIDITY',
        placeholder: 'Search city',
        search: 'SEARCH',
        latitude: 'Latitude',
        longitude: 'Longitude',
        error: 'Failed to load results',
        overview: {
            freezing_rain_heavy: 'Freezing heavy rain',
            freezing_rain: 'Freezing rain',
            freezing_rain_light: 'Freezing light rain',
            freezing_drizzle: 'Freezing drizzle',
            ice_pellets_heavy: 'Heavy ice pellets',
            ice_pellets: 'Ice pellets',
            ice_pellets_light: 'Light ice pellets',
            snow_heavy: 'Heavy snow',
            snow: 'Snow',
            snow_light: 'Light snow',
            flurries: 'Flurries',
            tstorm: 'Storm',
            rain_heavy: 'Heavy rain',
            rain: 'Rain',
            rain_light: 'Light rain',
            drizzle: 'Drizzle',
            fog_light: 'Light fog',
            fog: 'Fog',
            cloudy: 'Cloudy',
            mostly_cloudy: 'Mostly cloudy',
            partly_cloudy: 'Partly cloudy',
            mostly_clear: 'Mostly clear',
            clear: 'Clear',
        },
        weekDays: {
            0: 'Sunday',
            1: 'Monday',
            2: 'Tuesday',
            3: 'Wednesday',
            4: 'Thursday',
            5: 'Friday',
            6: 'Saturday',
        },
        months: {
            0: 'January',
            1: 'February',
            2: 'March',
            3: 'April',
            4: 'May',
            5: 'June',
            6: 'July',
            7: 'August',
            8: 'September',
            9: 'October',
            10: 'November',
            11: 'December',
        },
        codePhrase: 'Code word: Forecast',
    },
    ru: {
        feels: 'ОЩУЩАЕТСЯ:',
        wind: 'ВЕТЕР:',
        wind_unit: 'M/C',
        humidity: 'ВЛАЖНОСТЬ:',
        placeholder: 'Найти город',
        search: 'ПОИСК',
        latitude: 'Широта',
        longitude: 'Долгота',
        error: 'Не удалось загрузить результаты',
        overview: {
            freezing_rain_heavy: 'Cильный снег с дождем',
            freezing_rain: 'Cнег с дождем',
            freezing_rain_light: 'Cнег с дождем',
            freezing_drizzle: 'Изморозь',
            ice_pellets_heavy: 'Сильный град',
            ice_pellets: 'Град',
            ice_pellets_light: 'Град',
            snow_heavy: 'Сильный снег',
            snow: 'Снег',
            snow_light: 'Небольшой снег',
            flurries: 'Шквалистый ветер',
            tstorm: 'Шторм',
            rain_heavy: 'Сильный дождь',
            rain: 'Дождь',
            rain_light: 'Небольшой дождь',
            drizzle: 'Моросящий дождь',
            fog_light: 'Туман',
            fog: 'Туман',
            cloudy: 'Облачно',
            mostly_cloudy: 'Значительная облачность',
            partly_cloudy: 'Облачно с прояснениями',
            mostly_clear: 'Малооблачно',
            clear: 'Ясно',
        },
        weekDays: {
            0: 'Воскресенье',
            1: 'Понедельник',
            2: 'Вторник',
            3: 'Среда',
            4: 'Четверг',
            5: 'Пятница',
            6: 'Суббота',
        },
        months: {
            0: 'Январь',
            1: 'Февраль',
            2: 'Март',
            3: 'Апрель',
            4: 'Май',
            5: 'Июнь',
            6: 'Июль',
            7: 'Август',
            8: 'Сентябрь',
            9: 'Октябрь',
            10: 'Ноябрь',
            11: 'Декабрь',
        },
        codePhrase: 'Кодовое слово: Погода',
    },
    be: {
        feels: 'АДЧУВАЕЦЦА:',
        wind: 'ВЕЦЕР:',
        wind_unit: 'M/C',
        humidity: 'ВІЛЬГОТНАСЦЬ:',
        placeholder: 'Знайсці горад',
        search: 'ПОШУК',
        latitude: 'Шырата',
        longitude: 'Даўгата',
        error: 'Не атрымалася загрузіць вынікі',
        overview: {
            freezing_rain_heavy: 'Моцны снег з дажджом',
            freezing_rain: 'Cнег з дажджом',
            freezing_rain_light: 'Cнег з дажджом',
            freezing_drizzle: 'шэрань',
            ice_pellets_heavy: 'Моцны град',
            ice_pellets: 'Град',
            ice_pellets_light: 'Град',
            snow_heavy: 'Моцны снег',
            snow: 'Снег',
            snow_light: 'Невялікі снег',
            flurries: 'Шквалісты вецер',
            tstorm: 'Шторм',
            rain_heavy: 'Моцны дождж',
            rain: 'Дождж',
            rain_light: 'Невялікі дождж',
            drizzle: 'Дробны дождж',
            fog_light: 'Туман',
            fog: 'Туман',
            cloudy: 'Воблачна',
            mostly_cloudy: 'Значная воблачнасць',
            partly_cloudy: 'Пагодна',
            mostly_clear: 'Малавоблачна',
            clear: 'Ясна',
        },
        weekDays: {
            0: 'Нядзеля',
            1: 'Панядзелак',
            2: 'Аўторак',
            3: 'Серада',
            4: 'Чацвер',
            5: 'Пятніца',
            6: 'Субота',
        },
        months: {
            0: 'Студзень',
            1: 'Люты',
            2: 'Сакавік',
            3: 'Красавік',
            4: 'Мая',
            5: 'Чэрвень',
            6: 'Ліпень',
            7: 'Жнівень',
            8: 'Верасень',
            9: 'Кастрычнік',
            10: 'Лістапад',
            11: 'Снежань',
        },
        codePhrase: 'Кодавае слова: Погода',
    },
};

export default localization;
