const localization = {
    en: {
        feels: 'FEELS LIKE:',
        wind: 'WIND:',
        wind_unit: 'M/S',
        humidity: 'HUMIDITY',
        placeholder: 'Search city or ZIP',
        search: 'SEARCH',
        latitude: 'Latitude',
        longitude: 'Longitude',
        overview: {
            freezing_rain_heavy: 'Freezing heavy rain',
            freezing_rain: 'Freezing rain',
            freezing_rain_light: 'Freezing light rain',
            freezing_drizzle: 'Freezing drizzle',
            ice_pellets_heavy: 'Heavy ice pellets',
            ice_pellets: 'Ice pellets',
            ice_pellets_light: 'Light ice pellets',
            snow_heavy: 'Heavy snow',
            snow: 'Snow',
            snow_light: 'Light snow',
            flurries: 'Flurries',
            tstorm: 'Storm',
            rain_heavy: 'Heavy rain',
            rain: 'Rain',
            rain_light: 'Light rain',
            drizzle: 'Drizzle',
            fog_light: 'Light fog',
            fog: 'Fog',
            cloudy: 'Cloudy',
            mostly_cloudy: 'Mostly cloudy',
            partly_cloudy: 'Partly cloudy',
            mostly_clear: 'Mostly clear',
            clear: 'Clear',
        },
    },
    ru: {
        feels: 'ОЩУЩАЕТСЯ:',
        wind: 'ВЕТЕР:',
        wind_unit: 'M/C',
        humidity: 'ВЛАЖНОСТЬ:',
        placeholder: 'Найти город или индекс',
        search: 'ПОИСК',
        latitude: 'Широта',
        longitude: 'Долгота',
        overview: {
            freezing_rain_heavy: 'Cильный снег с дождем',
            freezing_rain: 'Cнег с дождем',
            freezing_rain_light: 'Cнег с дождем',
            freezing_drizzle: 'Изморозь',
            ice_pellets_heavy: 'Сильный град',
            ice_pellets: 'Град',
            ice_pellets_light: 'Град',
            snow_heavy: 'Сильный снег',
            snow: 'Снег',
            snow_light: 'Небольшой снег',
            flurries: 'Шквалистый ветер',
            tstorm: 'Шторм',
            rain_heavy: 'Сильный дождь',
            rain: 'Дождь',
            rain_light: 'Небольшой дождь',
            drizzle: 'Моросящий дождь',
            fog_light: 'Туман',
            fog: 'Туман',
            cloudy: 'Облачно',
            mostly_cloudy: 'Значительная облачность',
            partly_cloudy: 'Облачно с прояснениями',
            mostly_clear: 'Малооблачно',
            clear: 'Ясно',
        },
    },
    be: {
        feels: 'АДЧУВАЕЦЦА:',
        wind: 'ВЕЦЕР:',
        wind_unit: 'M/C',
        humidity: 'ВІЛЬГОТНАСЦЬ:',
        placeholder: 'Знайсці горад ці індэкс',
        search: 'ПОШУК',
        latitude: 'Шырата',
        longitude: 'Даўгата',
        overview: {
            freezing_rain_heavy: 'Моцны снег з дажджом',
            freezing_rain: 'Cнег з дажджом',
            freezing_rain_light: 'Cнег з дажджом',
            freezing_drizzle: 'шэрань',
            ice_pellets_heavy: 'Моцны град',
            ice_pellets: 'Град',
            ice_pellets_light: 'Град',
            snow_heavy: 'Моцны снег',
            snow: 'Снег',
            snow_light: 'Невялікі снег',
            flurries: 'Шквалісты вецер',
            tstorm: 'Шторм',
            rain_heavy: 'Моцны дождж',
            rain: 'Дождж',
            rain_light: 'Невялікі дождж',
            drizzle: 'Дробны дождж',
            fog_light: 'Туман',
            fog: 'Туман',
            cloudy: 'Воблачна',
            mostly_cloudy: 'Значная воблачнасць',
            partly_cloudy: 'Пагодна',
            mostly_clear: 'Малавоблачна',
            clear: 'Ясна',
        },
    },
};

export default localization;
