const tempCards = [
    {
        word: 'agree',
        image: 'files/01_0001.jpg',
        audio: 'files/01_0001.mp3',
        audioMeaning: 'files/01_0001_meaning.mp3',
        audioExample: 'files/01_0001_example.mp3',
        textMeaning: 'To <i>agree</i> is to have the same opinion or belief as another person.',
        textExample: 'The students <b>agree</b> they have too much homework.',
        transcription: '[əgríː]',
    },
    {
        word: 'alcohol',
        image: 'files/01_0002.jpg',
        audio: 'files/01_0002.mp3',
        audioMeaning: 'files/01_0002_meaning.mp3',
        audioExample: 'files/01_0002_example.mp3',
        textMeaning: '<i>Alcohol</i> is a type of drink that can make people drunk.',
        textExample:
            'A person should not drive a car after he or she has been drinking <b>alcohol</b>.',
        transcription: '[ǽlkəhɔ̀ːl]',
    },
    {
        word: 'boat',
        image: 'files/01_0005.jpg',
        audio: 'files/01_0005.mp3',
        audioMeaning: 'files/01_0005_meaning.mp3',
        audioExample: 'files/01_0005_example.mp3',
        textMeaning: 'A <i>boat</i> is a vehicle that moves across water.',
        textExample: 'There is a small <b>boat</b> on the lake.',
        transcription: '[bout]',
    },
    {
        word: 'arrive',
        image: 'files/01_0003.jpg',
        audio: 'files/01_0003.mp3',
        audioMeaning: 'files/01_0003_meaning.mp3',
        audioExample: 'files/01_0003_example.mp3',
        textMeaning: 'To <i>arrive</i> is to get somewhere.',
        textExample: 'They <b>arrived</b> at school at 7 a.m.',
        transcription: '[əráiv]',
    },
    {
        word: 'August',
        image: 'files/01_0004.jpg',
        audio: 'files/01_0004.mp3',
        audioMeaning: 'files/01_0004_meaning.mp3',
        audioExample: 'files/01_0004_example.mp3',
        textMeaning: '<i>August</i> is the eighth month of the year.',
        textExample: 'Is your birthday in <b>August</b>?',
        transcription: '[ɔ́ːgəst]',
    },
    {
        word: 'breakfast',
        image: 'files/01_0006.jpg',
        audio: 'files/01_0006.mp3',
        audioMeaning: 'files/01_0006_meaning.mp3',
        audioExample: 'files/01_0006_example.mp3',
        textMeaning: '<i>Breakfast</i> is the morning meal.',
        textExample: 'I ate eggs for <b>breakfast</b>.',
        transcription: '[brekfəst]',
    },
    {
        word: 'camera',
        image: 'files/01_0007.jpg',
        audio: 'files/01_0007.mp3',
        audioMeaning: 'files/01_0007_meaning.mp3',
        audioExample: 'files/01_0007_example.mp3',
        textMeaning: 'A <i>camera</i> is a piece of equipment that takes pictures.',
        textExample: 'I brought my <b>camera</b> on my vacation.',
        transcription: '[kǽmərə]',
    },
    {
        word: 'capital',
        image: 'files/01_0008.jpg',
        audio: 'files/01_0008.mp3',
        audioMeaning: 'files/01_0008_meaning.mp3',
        audioExample: 'files/01_0008_example.mp3',
        textMeaning: 'A <i>capital</i> is a city where a country’s government is based.',
        textExample: 'The <b>capital</b> of the United States is Washington, D.C.',
        transcription: '[kæpətl]',
    },
    {
        word: 'catch',
        image: 'files/01_0009.jpg',
        audio: 'files/01_0009.mp3',
        audioMeaning: 'files/01_0009_meaning.mp3',
        audioExample: 'files/01_0009_example.mp3',
        textMeaning: 'To <i>catch</i> is to grab or get something.',
        textExample: 'Did you <b>catch</b> the ball during the baseball game?',
        transcription: '[kætʃ]',
    },
    {
        word: 'duck',
        image: 'files/01_0010.jpg',
        audio: 'files/01_0010.mp3',
        audioMeaning: 'files/01_0010_meaning.mp3',
        audioExample: 'files/01_0010_example.mp3',
        textMeaning: 'A <i>duck</i> is a small water bird.',
        textExample: 'People feed <b>ducks</b> at the lake.',
        transcription: '[dʌk]',
    },
];

export default tempCards;
